chcp 65001
@echo off

md "Origem e Evolução do Trabalho\Historia do Trabalho no Brasil\Brasil República"
md "Origem e Evolução do Trabalho\Historia do Trabalho no Brasil\Brasil Império"
md "Origem e Evolução do Trabalho\Historia do Trabalho no Brasil\Brasil Colônia"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei de 13 de setembro de 1830"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 108, de 11 de outubro de 1837"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 556, de 25 de junho de 1850"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 2827, de 15 de março de 1879"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 1.313, de 17 de janeiro de 1891"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto Legislativo n.º 4.682, de 24 de janeiro de 1923"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 16.027, de 30 de abril de 1923"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 4.859, de 26 de setembro de 1924"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 4.982, de 24 de dezembro de 1925"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 5.083, de 1° de dezembro de 1926"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 17.496, de 30 de outubro de 1926"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 5.109, de 20 de dezembro de 1926"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 19.433, de 23 de novembro de 1930"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 19.482, de 12 de dezembro de 1930"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 19.770, de 19 de março de 1931"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 21.175, de 21 de março de 1932"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Em julho de 1934"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Em novembro de 1937"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 1.402, de 5 de julho de 1939"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 1.237, de 2 de maio de 1939"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 2.162, de 1° de maio de 1940"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\1° de maio de 1941"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-Lei n.º 5.452, de 1° de maio de 1943"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 9.070, de 15 de março de 1946"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 9.502, de 23 de julho de 1946"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 41.721, de 25 de junho de 1957"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.066, de maio de 1962"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4214, de 2 de março de 1963"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.266, de outubro de 1963"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4330, de 1° de junho de 1964"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.589, de 11 de dezembro de 1964"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.725, de 13 de julho de 1965"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 5.107, de 13 de setembro de 1966"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 229, de 28 de fevereiro de 1967"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 564, de 1° de maio de 1969"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n. ° 5.584, de 26 de junho de 1970"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n °. 5.889, de 8 de junho de 1973"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\1988"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 7.783, de 28 de junho de 1989"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 2.100, de 20 de dezembro de 1996"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\2006"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 11.948, de 16 de junho de 2009"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.551, de 15 de dezembro de 2011"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.513, de 26 de outubro de 2011"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.440, de 7 de julho de 2011"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.382, de 25 de fevereiro de 2011"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.506, de 11 de outubro de 2011"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.761, de 27 de dezembro de 2012"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Emenda Constitucional n.º 72, de 2 de abril de 2013"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Medida Provisória n.º 665, de 30 de dezembro de 2014"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 13.467, de 13 de julho de 2017"
md "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 13.429, de 31 de março de 2017"

md "CNT\A Criação do CNT\Lei Eloy Chaves (Lei nº 4.682-23)"
md "CNT\A Criação do CNT\Novo Regulamento do Conselho Nacional do Trabalho"
md "CNT\A Criação do CNT\Criação do Ministério do Trabalho"
md "CNT\A Criação do CNT\Comissões Mistas e Juntas de Conciliação e Julgamento 1930-1943"
md "CNT\A Criação do CNT\Constituição de 1934"
md "CNT\A Criação do CNT\Acervo CNT"
md "CNT\Organograma Evolutivo\Decreto 16.027, de 30-04-1923"
md "CNT\Organograma Evolutivo\Decreto 18.074, de 19-01-1928"
md "CNT\Ex-Presidentes\Augusto Viveiros de Castro 1923 a 1925"
md "CNT\Ex-Presidentes\Ataulpho Nápoles de Paiva 1925 a 1930"
md "CNT\Ex-Presidentes\Mário de Andrade Ramos 1931 a 1933"
md "CNT\Ex-Presidentes\Cassiano Tavares Bastos 1933 a 1935"
md "CNT\Ex-Presidentes\Francisco Barbosa Rezende 1935 a 1942"
md "CNT\Ex-Presidentes\Silvestre Péricles de Gois 1942 a 1943"
md "CNT\Ex-Presidentes\Filinto Muller 1943 a 1945"
md "CNT\Ex-Presidentes\Geraldo Montedônio  Bezerra de Menezes 1946 a 1951"

md "Justiça do Trabalho\No Mundo"
md "Justiça do Trabalho\No Brasil"
md "Justiça do Trabalho\Autores\CSJT"
md "Justiça do Trabalho\Autores\TST"
md "Justiça do Trabalho\Autores\TRTs"
md "Justiça do Trabalho\Autores\Vara do Trabalho"
md "Justiça do Trabalho\Autores\PGT"
md "Justiça do Trabalho\Autores\ENAMAT"
md "Justiça do Trabalho\Autores\ANAMATRA"

md "TST\Fatos Históricos\A JT e o Poder Judiciário"
md "TST\Fatos Históricos\A Divisão do TST em Turmas"
md "TST\Fatos Históricos\TST em Brasília"
md "TST\Fatos Históricos\A bandeira do TST"
md "TST\Fatos Históricos\Mulheres pioneiras no TST\Ministra Cnéa Cimini Moreira de Oliveira"
md "TST\Fatos Históricos\Mulheres pioneiras no TST\Ministra Maria Cristina Irigoyen Peduzzi"
md "TST\Fatos Históricos\Utilização de serviços de Internet"
md "TST\Fatos Históricos\Reformas do Poder Judiciário"
md "TST\Fatos Históricos\Nova Sede TST"
md "TST\Fatos Históricos\Lei do Processo Eletrônico"
md "TST\Fatos Históricos\PJe-TST"
md "TST\Fatos Históricos\BNDT"
md "TST\Programas Institucionais\Conciliação Trabalhista"
md "TST\Programas Institucionais\Execução Trabalhista"
md "TST\Programas Institucionais\Trabalho Seguro"
md "TST\Programas Institucionais\Pje"
md "TST\Programas Institucionais\Programa de Combate ao Trabalho Infantil e Estimulo à Aprendizagem"
md "TST\Programas Institucionais\História Oral"
md "TST\Programas Institucionais\JusLaboris – Biblioteca Digital da Justiça do Trabalho"
md "TST\Programas Institucionais\Arquivoteca Digital"
md "TST\70 Anos em Acórdãos\Ministro Alexandre de Souza Agra Belmonte"
md "TST\70 Anos em Acórdãos\Ministro Aloysio Corrêa da Veiga"
md "TST\70 Anos em Acórdãos\Ministro Antônio José de Barros Levenhagen"
md "TST\70 Anos em Acórdãos\Ministro Augusto César Leite de Carvalho"
md "TST\70 Anos em Acórdãos\Ministro Cláudio Mascarenhas Brandão"
md "TST\70 Anos em Acórdãos\Ministra Delaíde Alves Miranda Arantes"
md "TST\70 Anos em Acórdãos\Ministra Dora Maria da Costa"
md "TST\70 Anos em Acórdãos\Ministro Douglas Alencar Rodrigues"
md "TST\70 Anos em Acórdãos\Ministro Emmanoel Pereira"
md "TST\70 Anos em Acórdãos\Ministro Fernando Eizo Ono"
md "TST\70 Anos em Acórdãos\Ministro Guilherme Caputo Bastos"
md "TST\70 Anos em Acórdãos\Ministro Hugo Carlos Scheuermann"
md "TST\70 Anos em Acórdãos\Ministro Ives Gandra da Silva Martins Filho"
md "TST\70 Anos em Acórdãos\Ministro João Batista Brito Pereira"
md "TST\70 Anos em Acórdãos\Ministro João Oreste Dalazen"
md "TST\70 Anos em Acórdãos\Ministro José Roberto Freire Pimenta"
md "TST\70 Anos em Acórdãos\Ministra Kátia Magalhães Arruda"
md "TST\70 Anos em Acórdãos\Ministro Lélio Bentes Corrêa"
md "TST\70 Anos em Acórdãos\Ministro Luiz Philipe Vieira de Mello Filho"
md "TST\70 Anos em Acórdãos\Ministro Márcio Eurico Vitral Amaro"
md "TST\70 Anos em Acórdãos\Ministra Maria Cristina Irigoyen Peduzzi"
md "TST\70 Anos em Acórdãos\Ministra Maria de Assis Calsing"
md "TST\70 Anos em Acórdãos\Ministra Maria Helena Mallmann"
md "TST\70 Anos em Acórdãos\Ministro Maurício Godinho Delgado"
md "TST\70 Anos em Acórdãos\Ministro Renato de Lacerda Paiva"
md "TST\70 Anos em Acórdãos\Ministro Walmir Oliveira da Costa"
md "TST\70 Anos em Acórdãos\Ministro Antonio Maria Thaumaturgo Cortizo"
md "TST\70 Anos em Acórdãos\Ministro Arnaldo Lopes Sussekind"
md "TST\70 Anos em Acórdãos\Ministro Carlos Alberto Reis de Paula"
md "TST\70 Anos em Acórdãos\Ministro Carlos Coqueijo Torreão da Costa"
md "TST\70 Anos em Acórdãos\Ministra Cnéa Cimini Moreira de Oliveira"
md "TST\70 Anos em Acórdãos\Ministro Délio Maranhão"
md "TST\70 Anos em Acórdãos\Ministro Ermes Pedro Pedrassani"
md "TST\70 Anos em Acórdãos\Ministro Geraldo Montedônio Bezerra de Menezes"
md "TST\70 Anos em Acórdãos\Ministro Horácio Raymundo de Senna Pires"
md "TST\70 Anos em Acórdãos\Ministro Hylo Bezerra Gurgel"
md "TST\70 Anos em Acórdãos\Ministro Jeremias Marrocos de Moraes Pires"
md "TST\70 Anos em Acórdãos\Ministro José Luciano de Castilho Pereira"
md "TST\70 Anos em Acórdãos\Ministro José Simpliciano Fontes de Faria Fernandes"
md "TST\70 Anos em Acórdãos\Ministro Luiz José Guimarães Falcão"
md "TST\70 Anos em Acórdãos\Ministro Marco Aurélio Mendes de Farias Mello"
md "TST\70 Anos em Acórdãos\Ministro Milton de Moura França"
md "TST\70 Anos em Acórdãos\Ministro Mozart Victor Russomano"
md "TST\70 Anos em Acórdãos\Ministro Nelson Tapajós"
md "TST\70 Anos em Acórdãos\Ministro Orlando Coutinho"
md "TST\70 Anos em Acórdãos\Ministro Orlando Teixeira da Costa"
md "TST\70 Anos em Acórdãos\Ministra Rosa Maria Weber"
md "TST\70 Anos em Acórdãos\Ministro Ursulino Santos Filho"
md "TST\70 Anos em Acórdãos\Ministro Vantuil Abdala"

md "CSJT\Criação"
md "CSJT\Ex-Presidentes\Ministro Antonio de Barros Levenhagen"
md "CSJT\Ex-Presidentes\Ministro Carlos Alberto Reis de Paula"
md "CSJT\Ex-Presidentes\Ministro João Oreste Dalazen"
md "CSJT\Ex-Presidentes\Ministro Milton de Moura França"
md "CSJT\Ex-Presidentes\Ministro Rider de Brito"
md "CSJT\Ex-Presidentes\Ministro Ronaldo Leal"
md "CSJT\Ex-Presidentes\Ministro Vantuil Abdala"
md "CSJT\Membros\Ministro João Batista Brito Pereira"
md "CSJT\Membros\Ministro Renato de Lacerda Paiva"
md "CSJT\Membros\Ministro Lelio Bentes Corrêa"
md "CSJT\Membros\Ministro Marcio Eurico Vitral"
md "CSJT\Membros\Ministro Walmir Oliveira da Costa "
md "CSJT\Membros\Ministro Maurício Godinho Delgado "
md "CSJT\Membros\Desembargador Gracio Ricardo Barboza Petrone"
md "CSJT\Membros\Desembargador Fabio Túlio Correia Ribeiro"
md "CSJT\Membros\Desembargadora Suzy Elizabeth Cavalcante Koury"
md "CSJT\Membros\Desembargador Fernando da Silva borges"
md "CSJT\Membros\Desembargador Platon Teixeira de Azevedo Filho"

md "Curiosidades\Justiça e Números"
md "Curiosidades\Dicionário de profissões pouco comuns\Chanfrador"
md "Curiosidades\Dicionário de profissões pouco comuns\Colometrista"
md "Curiosidades\Dicionário de profissões pouco comuns\Duteiro"
md "Curiosidades\Dicionário de profissões pouco comuns\Espeleólogo"
md "Curiosidades\Dicionário de profissões pouco comuns\Extrusor de sopro"
md "Curiosidades\Dicionário de profissões pouco comuns\Faccionista"
md "Curiosidades\Dicionário de profissões pouco comuns\Faquista"
md "Curiosidades\Dicionário de profissões pouco comuns\Herpetólogo"
md "Curiosidades\Dicionário de profissões pouco comuns\Ficólogo"
md "Curiosidades\Dicionário de profissões pouco comuns\Guaribador"
md "Curiosidades\Dicionário de profissões pouco comuns\Ictiólogo"
md "Curiosidades\Dicionário de profissões pouco comuns\Madrilador"
md "Curiosidades\Dicionário de profissões pouco comuns\Mirmecologista"
md "Curiosidades\Dicionário de profissões pouco comuns\Micologista"
md "Curiosidades\Dicionário de profissões pouco comuns\Migueiro-Trigueiro"
md "Curiosidades\Dicionário de profissões pouco comuns\Ornitóloga"
md "Curiosidades\Dicionário de profissões pouco comuns\Papiloscopista"
md "Curiosidades\Dicionário de profissões pouco comuns\Piloteiro"
md "Curiosidades\Dicionário de profissões pouco comuns\Tricologista"
md "Curiosidades\Você sabia\Dia do Trabalho nos Estados Unidos"
md "Curiosidades\Você sabia\Dia do Trabalho na Austrália"
md "Curiosidades\Você sabia\Dia do Trabalho no Brasil"
md "Curiosidades\Você sabia\Dia do Trabalho no Mundo"
md "Curiosidades\Você sabia\Beijo 2348-72"
md "Curiosidades\Você sabia\Decreto nº. 19.482, de 12-12-1930"
md "Curiosidades\Você sabia\Tratado de Versalhes"
md "Curiosidades\Você sabia\Férias"

copy NUL "Origem e Evolução do Trabalho\Historia do Trabalho no Brasil\Brasil República.html"
copy NUL "Origem e Evolução do Trabalho\Historia do Trabalho no Brasil\Brasil Império.html"
copy NUL "Origem e Evolução do Trabalho\Historia do Trabalho no Brasil\Brasil Colônia.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei de 13 de setembro de 1830\Lei de 13 de setembro de 1830.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 108, de 11 de outubro de 1837\Lei n.º 108, de 11 de outubro de 1837.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 556, de 25 de junho de 1850\Lei n.º 556, de 25 de junho de 1850.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 2827, de 15 de março de 1879\Decreto n.º 2827, de 15 de março de 1879.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 1.313, de 17 de janeiro de 1891\Decreto n.º 1.313, de 17 de janeiro de 1891.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto Legislativo n.º 4.682, de 24 de janeiro de 1923\Decreto Legislativo n.º 4.682, de 24 de janeiro de 1923.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 16.027, de 30 de abril de 1923\Decreto n.º 16.027, de 30 de abril de 1923.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 4.859, de 26 de setembro de 1924\Decreto n.º 4.859, de 26 de setembro de 1924.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 4.982, de 24 de dezembro de 1925\Decreto n.º 4.982, de 24 de dezembro de 1925.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 5.083, de 1° de dezembro de 1926\Decreto n.º 5.083, de 1° de dezembro de 1926.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 17.496, de 30 de outubro de 1926\Decreto n.º 17.496, de 30 de outubro de 1926.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 5.109, de 20 de dezembro de 1926\Decreto n.º 5.109, de 20 de dezembro de 1926.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 19.433, de 23 de novembro de 1930\Decreto n.º 19.433, de 23 de novembro de 1930.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 19.482, de 12 de dezembro de 1930\Decreto n.º 19.482, de 12 de dezembro de 1930.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 19.770, de 19 de março de 1931\Decreto n.º 19.770, de 19 de março de 1931.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 21.175, de 21 de março de 1932\Decreto n.º 21.175, de 21 de março de 1932.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Em julho de 1934\Em julho de 1934.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Em novembro de 1937\Em novembro de 1937.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 1.402, de 5 de julho de 1939\Decreto-lei n.º 1.402, de 5 de julho de 1939.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 1.237, de 2 de maio de 1939\Decreto-lei n.º 1.237, de 2 de maio de 1939.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 2.162, de 1° de maio de 1940\Decreto-lei n.º 2.162, de 1° de maio de 1940.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\1° de maio de 1941\1° de maio de 1941.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-Lei n.º 5.452, de 1° de maio de 1943\Decreto-Lei n.º 5.452, de 1° de maio de 1943.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 9.070, de 15 de março de 1946\Decreto-lei n.º 9.070, de 15 de março de 1946.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 9.502, de 23 de julho de 1946\Decreto n.º 9.502, de 23 de julho de 1946.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 41.721, de 25 de junho de 1957\Decreto n.º 41.721, de 25 de junho de 1957.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.066, de maio de 1962\Lei n.º 4.066, de maio de 1962.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4214, de 2 de março de 1963\Lei n.º 4214, de 2 de março de 1963.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.266, de outubro de 1963\Lei n.º 4.266, de outubro de 1963.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4330, de 1° de junho de 1964\Lei n.º 4330, de 1° de junho de 1964.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.589, de 11 de dezembro de 1964\Lei n.º 4.589, de 11 de dezembro de 1964.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 4.725, de 13 de julho de 1965\Lei n.º 4.725, de 13 de julho de 1965.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 5.107, de 13 de setembro de 1966\Lei n.º 5.107, de 13 de setembro de 1966.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 229, de 28 de fevereiro de 1967\Decreto n.º 229, de 28 de fevereiro de 1967.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto-lei n.º 564, de 1° de maio de 1969\Decreto-lei n.º 564, de 1° de maio de 1969.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n. ° 5.584, de 26 de junho de 1970\Lei n. ° 5.584, de 26 de junho de 1970.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n °. 5.889, de 8 de junho de 1973\Lei n °. 5.889, de 8 de junho de 1973.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\1988\1988.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 7.783, de 28 de junho de 1989\Lei n.º 7.783, de 28 de junho de 1989.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Decreto n.º 2.100, de 20 de dezembro de 1996\Decreto n.º 2.100, de 20 de dezembro de 1996.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\2006\2006.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 11.948, de 16 de junho de 2009\Lei n.º 11.948, de 16 de junho de 2009.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.551, de 15 de dezembro de 2011\Lei n.º 12.551, de 15 de dezembro de 2011.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.513, de 26 de outubro de 2011\Lei n.º 12.513, de 26 de outubro de 2011.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.440, de 7 de julho de 2011\Lei n.º 12.440, de 7 de julho de 2011.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.382, de 25 de fevereiro de 2011\Lei n.º 12.382, de 25 de fevereiro de 2011.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.506, de 11 de outubro de 2011\Lei n.º 12.506, de 11 de outubro de 2011.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 12.761, de 27 de dezembro de 2012\Lei n.º 12.761, de 27 de dezembro de 2012.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Emenda Constitucional n.º 72, de 2 de abril de 2013\Emenda Constitucional n.º 72, de 2 de abril de 2013.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Medida Provisória n.º 665, de 30 de dezembro de 2014\Medida Provisória n.º 665, de 30 de dezembro de 2014.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 13.467, de 13 de julho de 2017\Lei n.º 13.467, de 13 de julho de 2017.html"
copy NUL "Origem e Evolução do Trabalho\Legislação Trabalhista\Lei n.º 13.429, de 31 de março de 2017\Lei n.º 13.429, de 31 de março de 2017.html"

copy NUL "CNT\A Criação do CNT\Lei Eloy Chaves (Lei nº 4.682-23)\Lei Eloy Chaves (Lei nº 4.682-23).html"
copy NUL "CNT\A Criação do CNT\Novo Regulamento do Conselho Nacional do Trabalho\Novo Regulamento do Conselho Nacional do Trabalho.html"
copy NUL "CNT\A Criação do CNT\Criação do Ministério do Trabalho\Criação do Ministério do Trabalho.html"
copy NUL "CNT\A Criação do CNT\Comissões Mistas e Juntas de Conciliação e Julgamento 1930-1943\Comissões Mistas e Juntas de Conciliação e Julgamento 1930-1943.html"
copy NUL "CNT\A Criação do CNT\Constituição de 1934\Constituição de 1934.html"
copy NUL "CNT\A Criação do CNT\Acervo CNT\Acervo CNT.html"
copy NUL "CNT\Organograma Evolutivo\Decreto 16.027, de 30-04-1923\Decreto 16.027, de 30-04-1923.html"
copy NUL "CNT\Organograma Evolutivo\Decreto 18.074, de 19-01-1928\Decreto 18.074, de 19-01-1928.html"
copy NUL "CNT\Ex-Presidentes\Augusto Viveiros de Castro 1923 a 1925\Augusto Viveiros de Castro 1923 a 1925.html"
copy NUL "CNT\Ex-Presidentes\Ataulpho Nápoles de Paiva 1925 a 1930\Ataulpho Nápoles de Paiva 1925 a 1930.html"
copy NUL "CNT\Ex-Presidentes\Mário de Andrade Ramos 1931 a 1933\Mário de Andrade Ramos 1931 a 1933.html"
copy NUL "CNT\Ex-Presidentes\Cassiano Tavares Bastos 1933 a 1935\Cassiano Tavares Bastos 1933 a 1935.html"
copy NUL "CNT\Ex-Presidentes\Francisco Barbosa Rezende 1935 a 1942\Francisco Barbosa Rezende 1935 a 1942.html"
copy NUL "CNT\Ex-Presidentes\Silvestre Péricles de Gois 1942 a 1943\Silvestre Péricles de Gois 1942 a 1943.html"
copy NUL "CNT\Ex-Presidentes\Filinto Muller 1943 a 1945\Filinto Muller 1943 a 1945.html"
copy NUL "CNT\Ex-Presidentes\Geraldo Montedônio  Bezerra de Menezes 1946 a 1951\Geraldo Montedônio  Bezerra de Menezes 1946 a 1951.html"

copy NUL "Justiça do Trabalho\No Mundo\No Mundo.html"
copy NUL "Justiça do Trabalho\No Brasil\No Brasil.html"
copy NUL "Justiça do Trabalho\Autores\CSJT\CSJT.html"
copy NUL "Justiça do Trabalho\Autores\TST\TST.html"
copy NUL "Justiça do Trabalho\Autores\TRTs\TRTs.html"
copy NUL "Justiça do Trabalho\Autores\Vara do Trabalho\Vara do Trabalho.html"
copy NUL "Justiça do Trabalho\Autores\PGT\PGT.html"
copy NUL "Justiça do Trabalho\Autores\ENAMAT\ENAMAT.html"
copy NUL "Justiça do Trabalho\Autores\ANAMATRA\ANAMATRA.html"

copy NUL "TST\Fatos Históricos\A JT e o Poder Judiciário\A JT e o Poder Judiciário.html"
copy NUL "TST\Fatos Históricos\A Divisão do TST em Turmas\A Divisão do TST em Turmas.html"
copy NUL "TST\Fatos Históricos\TST em Brasília\TST em Brasília.html"
copy NUL "TST\Fatos Históricos\A bandeira do TST\A bandeira do TST.html"
copy NUL "TST\Fatos Históricos\Mulheres pioneiras no TST\Ministra Cnéa Cimini Moreira de Oliveira\Ministra Cnéa Cimini Moreira de Oliveira.html"
copy NUL "TST\Fatos Históricos\Mulheres pioneiras no TST\Ministra Maria Cristina Irigoyen Peduzzi\Ministra Maria Cristina Irigoyen Peduzzi.html"
copy NUL "TST\Fatos Históricos\Utilização de serviços de Internet\Utilização de serviços de Internet.html"
copy NUL "TST\Fatos Históricos\Reformas do Poder Judiciário\Reformas do Poder Judiciário.html"
copy NUL "TST\Fatos Históricos\Nova Sede TST\Nova Sede TST.html"
copy NUL "TST\Fatos Históricos\Lei do Processo Eletrônico\Lei do Processo Eletrônico.html"
copy NUL "TST\Fatos Históricos\PJe-TST\PJe-TST.html"
copy NUL "TST\Fatos Históricos\BNDT\BNDT.html"
copy NUL "TST\Programas Institucionais\Conciliação Trabalhista\Conciliação Trabalhista.html"
copy NUL "TST\Programas Institucionais\Execução Trabalhista\Execução Trabalhista.html"
copy NUL "TST\Programas Institucionais\Trabalho Seguro\Trabalho Seguro.html"
copy NUL "TST\Programas Institucionais\Pje\Pje.html"
copy NUL "TST\Programas Institucionais\Programa de Combate ao Trabalho Infantil e Estimulo à Aprendizagem\Programa de Combate ao Trabalho Infantil e Estimulo à Aprendizagem.html"
copy NUL "TST\Programas Institucionais\História Oral\História Oral.html"
copy NUL "TST\Programas Institucionais\JusLaboris – Biblioteca Digital da Justiça do Trabalho\JusLaboris – Biblioteca Digital da Justiça do Trabalho.html"
copy NUL "TST\Programas Institucionais\Arquivoteca Digital\Arquivoteca Digital.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Alexandre de Souza Agra Belmonte\Ministro Alexandre de Souza Agra Belmonte.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Aloysio Corrêa da Veiga\Ministro Aloysio Corrêa da Veiga.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Antônio José de Barros Levenhagen\Ministro Antônio José de Barros Levenhagen.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Augusto César Leite de Carvalho\Ministro Augusto César Leite de Carvalho.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Cláudio Mascarenhas Brandão\Ministro Cláudio Mascarenhas Brandão.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Delaíde Alves Miranda Arantes\Ministra Delaíde Alves Miranda Arantes.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Dora Maria da Costa\Ministra Dora Maria da Costa.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Douglas Alencar Rodrigues\Ministro Douglas Alencar Rodrigues.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Emmanoel Pereira\Ministro Emmanoel Pereira.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Fernando Eizo Ono\Ministro Fernando Eizo Ono.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Guilherme Caputo Bastos\Ministro Guilherme Caputo Bastos.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Hugo Carlos Scheuermann\Ministro Hugo Carlos Scheuermann.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Ives Gandra da Silva Martins Filho\Ministro Ives Gandra da Silva Martins Filho.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro João Batista Brito Pereira\Ministro João Batista Brito Pereira.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro João Oreste Dalazen\Ministro João Oreste Dalazen.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro José Roberto Freire Pimenta\Ministro José Roberto Freire Pimenta.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Kátia Magalhães Arruda\Ministra Kátia Magalhães Arruda.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Lélio Bentes Corrêa\Ministro Lélio Bentes Corrêa.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Luiz Philipe Vieira de Mello Filho\Ministro Luiz Philipe Vieira de Mello Filho.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Márcio Eurico Vitral Amaro\Ministro Márcio Eurico Vitral Amaro.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Maria Cristina Irigoyen Peduzzi\Ministra Maria Cristina Irigoyen Peduzzi.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Maria de Assis Calsing\Ministra Maria de Assis Calsing.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Maria Helena Mallmann\Ministra Maria Helena Mallmann.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Maurício Godinho Delgado\Ministro Maurício Godinho Delgado.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Renato de Lacerda Paiva\Ministro Renato de Lacerda Paiva.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Walmir Oliveira da Costa\Ministro Walmir Oliveira da Costa.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Antonio Maria Thaumaturgo Cortizo\Ministro Antonio Maria Thaumaturgo Cortizo.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Arnaldo Lopes Sussekind\Ministro Arnaldo Lopes Sussekind.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Carlos Alberto Reis de Paula\Ministro Carlos Alberto Reis de Paula.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Carlos Coqueijo Torreão da Costa\Ministro Carlos Coqueijo Torreão da Costa.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Cnéa Cimini Moreira de Oliveira\Ministra Cnéa Cimini Moreira de Oliveira.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Délio Maranhão\Ministro Délio Maranhão.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Ermes Pedro Pedrassani\Ministro Ermes Pedro Pedrassani.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Geraldo Montedônio Bezerra de Menezes\Ministro Geraldo Montedônio Bezerra de Menezes.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Horácio Raymundo de Senna Pires\Ministro Horácio Raymundo de Senna Pires.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Hylo Bezerra Gurgel\Ministro Hylo Bezerra Gurgel.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Jeremias Marrocos de Moraes Pires\Ministro Jeremias Marrocos de Moraes Pires.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro José Luciano de Castilho Pereira\Ministro José Luciano de Castilho Pereira.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro José Simpliciano Fontes de Faria Fernandes\Ministro José Simpliciano Fontes de Faria Fernandes.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Luiz José Guimarães Falcão\Ministro Luiz José Guimarães Falcão.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Marco Aurélio Mendes de Farias Mello\Ministro Marco Aurélio Mendes de Farias Mello.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Milton de Moura França\Ministro Milton de Moura França.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Mozart Victor Russomano\Ministro Mozart Victor Russomano.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Nelson Tapajós\Ministro Nelson Tapajós.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Orlando Coutinho\Ministro Orlando Coutinho.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Orlando Teixeira da Costa\Ministro Orlando Teixeira da Costa.html"
copy NUL "TST\70 Anos em Acórdãos\Ministra Rosa Maria Weber\Ministra Rosa Maria Weber.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Ursulino Santos Filho\Ministro Ursulino Santos Filho.html"
copy NUL "TST\70 Anos em Acórdãos\Ministro Vantuil Abdala\Ministro Vantuil Abdala.html"

copy NUL "CSJT\Criação\Criação"
copy NUL "CSJT\Ex-Presidentes\Ministro Antonio de Barros Levenhagen\Ministro Antonio de Barros Levenhagen.html"
copy NUL "CSJT\Ex-Presidentes\Ministro Carlos Alberto Reis de Paula\Ministro Carlos Alberto Reis de Paula.html"
copy NUL "CSJT\Ex-Presidentes\Ministro João Oreste Dalazen\Ministro João Oreste Dalazen.html"
copy NUL "CSJT\Ex-Presidentes\Ministro Milton de Moura França\Ministro Milton de Moura França.html"
copy NUL "CSJT\Ex-Presidentes\Ministro Rider de Brito\Ministro Rider de Brito.html"
copy NUL "CSJT\Ex-Presidentes\Ministro Ronaldo Leal\Ministro Ronaldo Leal.html"
copy NUL "CSJT\Ex-Presidentes\Ministro Vantuil Abdala\Ministro Vantuil Abdala.html"
copy NUL "CSJT\Membros\Ministro João Batista Brito Pereira\Ministro João Batista Brito Pereira.html"
copy NUL "CSJT\Membros\Ministro Renato de Lacerda Paiva\Renato de Lacerda Paiva.html"
copy NUL "CSJT\Membros\Ministro Lelio Bentes Corrêa\Lelio Bentes Corrêa.html"
copy NUL "CSJT\Membros\Ministro Marcio Eurico Vitral\Marcio Eurico Vitral.html"
copy NUL "CSJT\Membros\Ministro Walmir Oliveira da Costa \Walmir Oliveira da Costa.html"
copy NUL "CSJT\Membros\Ministro Maurício Godinho Delgado\Maurício Godinho Delgado.html"
copy NUL "CSJT\Membros\Desembargador Gracio Ricardo Barboza Petrone\Gracio Ricardo Barboza Petrone.html"
copy NUL "CSJT\Membros\Desembargador Fabio Túlio Correia Ribeiro\Fabio Túlio Correia Ribeiro.html"
copy NUL "CSJT\Membros\Desembargadora Suzy Elizabeth Cavalcante Koury\Suzy Elizabeth Cavalcante Koury.html"
copy NUL "CSJT\Membros\Desembargador Fernando da Silva Borges\Fernando da Silva Borges.html"
copy NUL "CSJT\Membros\Desembargador Platon Teixeira de Azevedo Filho\Platon Teixeira de Azevedo Filho.html"

copy NUL "Curiosidades\Justiça e Números\Justiça e Números.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Chanfrador\Chanfrador.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Colometrista\Colometrista.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Duteiro\Duteiro.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Espeleólogo\Espeleólogo.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Extrusor de sopro\Extrusor de sopro.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Faccionista\Faccionista.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Faquista\Faquista.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Herpetólogo\Herpetólogo.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Ficólogo\Ficólogo.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Guaribador\Guaribador.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Ictiólogo\Ictiólogo.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Madrilador\Madrilador.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Mirmecologista\Mirmecologista.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Micologista\Micologista.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Migueiro-Trigueiro\Migueiro-Trigueiro.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Ornitóloga\Ornitóloga.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Papiloscopista\Papiloscopista.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Piloteiro\Piloteiro.html"
copy NUL "Curiosidades\Dicionário de profissões pouco comuns\Tricologista\Tricologista.html"
copy NUL "Curiosidades\Você sabia\Dia do Trabalho nos Estados Unidos\Dia do Trabalho nos Estados Unidos.html"
copy NUL "Curiosidades\Você sabia\Dia do Trabalho na Austrália\Dia do Trabalho na Austrália.html"
copy NUL "Curiosidades\Você sabia\Dia do Trabalho no Brasil\Dia do Trabalho no Brasil.html"
copy NUL "Curiosidades\Você sabia\Dia do Trabalho no Mundo\Dia do Trabalho no Mundo.html"
copy NUL "Curiosidades\Você sabia\Beijo 2348-72\Beijo 2348-72.html"
copy NUL "Curiosidades\Você sabia\Decreto nº. 19.482, de 12-12-1930\Decreto nº. 19.482, de 12-12-1930.html"
copy NUL "Curiosidades\Você sabia\Tratado de Versalhes\Tratado de Versalhes.html"
copy NUL "Curiosidades\Você sabia\Férias\Férias.html"

pause